# Generated by Django 6.0.1 on 2026-04-18 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(db_index=True, max_length=32, unique=True)),
                ('legal_name', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, max_length=16)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['cin'],
            },
        ),
        migrations.CreateModel(
            name='FraudSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('multi_claim_cin', 'Multiple claimants for same CIN'), ('gstin_reuse', 'GSTIN claimed frequently'), ('name_mismatch', 'Name mismatch across sources')], db_index=True, max_length=64)),
                ('severity', models.CharField(default='medium', max_length=16)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='verification.company')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_external_id', models.CharField(db_index=True, max_length=128)),
                ('cin', models.CharField(db_index=True, max_length=32)),
                ('gstin', models.CharField(db_index=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cin', 'claimant_external_id'], name='verificatio_cin_406c85_idx'), models.Index(fields=['gstin'], name='verificatio_gstin_a164ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(db_index=True, max_length=15, unique=True)),
                ('legal_name', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, max_length=16)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_records', to='verification.company')),
            ],
            options={
                'ordering': ['gstin'],
            },
        ),
    ]
