# Generated by Django 6.0.1 on 2026-04-19 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image', models.ImageField(upload_to='verifications/ids/')),
                ('selfie_image', models.ImageField(upload_to='verifications/selfies/')),
                ('extracted_name', models.CharField(blank=True, max_length=255)),
                ('face_similarity', models.FloatField(default=0.0)),
                ('liveness_passed', models.BooleanField(default=False)),
                ('name_match', models.BooleanField(default=False)),
                ('verification_confidence', models.IntegerField(default=0)),
                ('is_identity_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
