# Generated by Django 6.0.1 on 2026-04-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_userverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='masked_id_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
