# Generated by Django 6.0.1 on 2026-04-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_api', '0002_wallet_razorpay_grievance'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventenrollment',
            name='attendance_key',
            field=models.CharField(blank=True, db_index=True, help_text='Secret printed with ticket; embedded in QR for stronger check-in.', max_length=48),
        ),
    ]
