# Generated by Django 6.0.1 on 2026-04-18 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_headline_profile_location_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_docs',
            field=models.FileField(blank=True, null=True, upload_to='verifications/company_docs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='gov_id',
            field=models.FileField(blank=True, null=True, upload_to='verifications/gov_ids/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_boss',
            field=models.BooleanField(default=False, help_text='User claims company leadership; Green tier also needs verified company documents.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_company_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_company_verified',
            field=models.BooleanField(default=False, help_text='Admin verified company documents (required for Green tier).'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_gov_id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
