# Generated by Django 6.0.1 on 2026-04-18 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_organizers(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    EventOrganizerProfile = apps.get_model("accounts", "EventOrganizerProfile")
    for profile in Profile.objects.filter(is_gov_id_verified=True).select_related("user"):
        EventOrganizerProfile.objects.get_or_create(
            user=profile.user,
            defaults={"display_name": profile.name or profile.user.username},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_trust_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('public_contact', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_organizers, noop_reverse),
    ]
