# Generated by Django 6.0.1 on 2026-04-18 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_verified_user_from_gov(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    Profile.objects.filter(is_gov_id_verified=True).update(is_verified_user=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_event_organizer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='claim_type',
            field=models.CharField(blank=True, choices=[('', 'Not upgrading'), ('employee', 'Employee'), ('owner', 'Owner'), ('organiser', 'Event organiser')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_company_confirmed',
            field=models.BooleanField(default=False, help_text='Employer clicked approve link in affiliation email.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified_user',
            field=models.BooleanField(default=False, help_text='Verified user: may fundraise and host events (employee/owner/organiser paths).'),
        ),
        migrations.AddField(
            model_name='profile',
            name='owner_cin',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='owner_gstin',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='sandbox_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='sandbox_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeAffiliationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_verified_user_from_gov, noop_reverse),
    ]
